import { CATEGORIES, CATEGORY_COLORS } from './categories'
import { ROLE_NAVIGATION, DEFAULT_NAVIGATION } from './navigation'
import { QUESTION_TYPE, DIFFICULTY } from './quiz'
import { ROLES, ROLE_NAMES } from './roles'
import { DEPARTMENT_COLORS, DEPARTMENTS, DEPARTMENT_NAMES } from './userprofile'
import { STATUS_PROGRESS } from './userprogress'

export {
  CATEGORIES,
  CATEGORY_COLORS,
  ROLE_NAVIGATION,
  DEFAULT_NAVIGATION,
  QUESTION_TYPE,
  DIFFICULTY,
  ROLES,
  ROLE_NAMES,
  DEPARTMENT_COLORS,
  DEPARTMENTS,
  DEPARTMENT_NAMES,
  STATUS_PROGRESS,
}
